version: '3.8'
# docker-compose up -d

services:
  # postgres
  db: 
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  app:
    image: golang:1.16.0-alpine3.13
    restart: always
    command: sh -c "go run ./server/main.go"
    build: .
    working_dir: /app
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - db
    volumes: 
      - .:/app

networks:
  backend:

volumes:
  pgdata: